### ISSUE TITLE
eXist-db 3.0 stable

### ISSUE THREAD

**Issue by welblaud** [eXist-db/xquery-xproc-xmlcalabash-module#4]
I have just tried the example provided.

This exact code:

```
xquery version "3.0";

import module namespace xproc="http://exist-db.org/xproc";

let $simple-xproc as document-node() := document {
    \<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
            \<p:input port="source">
                    \<p:inline>
                            \<doc>Hello world!\</doc>
                    \</p:inline>
            \</p:input>
            \<p:output port="result"/>
            \<p:identity/>
    \</p:declare-step>
}

return
    xproc:process($simple-xproc)
```
… does not work because of slashes (eXide throws slashes are unecpected chars).

When I remove slashes:

```
xquery version "3.0";

import module namespace xproc="http://exist-db.org/xproc";

let $simple-xproc as document-node() := document {
    <p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
            <p:input port="source">
                    <p:inline>
                            <doc>Hello world!\</doc>
                    </p:inline>
            </p:input>
            <p:output port="result"/>
            <p:identity/>
    </p:declare-step>
}

return
    xproc:process($simple-xproc)
```
… it throws:

`Cannot compile xquery: exerr:ERROR error found while loading module xproc: Cannot find module class from EXPath repository: org.exist.xquery.xproc.Module`

Am I doing something wrong or is it still the issue from eXist-db 3.0RC2?

I am pretty sure I installed the XProc package via Package Manager and restarted eXist for sure.

**Comment by joewiz** [comment]
As described in https://github.com/eXist-db/xquery-xproc-xmlcalabash-module/issues/3#issuecomment-384318817, the sample code (I only tested the 2nd version here; slashes are not necessary) works with a current build of the project and eXist 4.1.0.
